### ISSUE TITLE
SCSS Implementation

### ISSUE THREAD

**Issue by MMadejsza** [MMadejsza/yoganka.pl#54]
### 📅 Deadline

10-11-2024

### 📝 Task Summary

Apply SCSS best practices

### 🗒️ Checklist/Additional Notes

- [x] Labeled?
- [x] Prioritized and scaled in projects?
- [x] Milestone?
- [x]  Files provided?

**Comment by MMadejsza** [comment]
SCSS applied:

- [ ] Nesting
- [ ] Mixins
- [ ] Variables and their mapping
- [ ] % templates
- [ ] @include and @extend clousules
- [ ] Proper code organization through partials
- [ ] @use and @forward implemented instead of @import
- [ ] Built-in functions for colors
- [ ] External links fetched into SCSS

Aside

- [ ]  Partners Logos quality enhanced
- [ ]  Overall layout bugs fixed (alignment etc)
- [ ]  Glide reinstalled through npm
- [ ]  Vite config updated
- [ ]  HTML clean up
- [ ] Favicon implemented
- [ ] Burger animation corrected
