### ISSUE TITLE
Check Vite for SCSS

### ISSUE THREAD

**Issue by MMadejsza** [MMadejsza/yoganka.pl#55]
### 📅 Deadline

10-11-2024

### 📝 Task Summary

Check if Vite properly serves SCSS files

### 🗒️ Checklist/Additional Notes

- [x] Labeled?
- [x] Prioritized and scaled in projects?
- [x] Milestone?
- [ ] Files provided?

**Comment by MMadejsza** [comment]
- [X] Vite checked
- [X] Config file updated
- [X] Dependencies updated (removed depreciated ones)
