### ISSUE TITLE
Yoganka templates

### ISSUE THREAD

**Issue by MMadejsza** [MMadejsza/yoganka.pl#58]
### 📅 Deadline

-

### 📝 Task Summary

Create templates for yoganka to update content for events and camps.
- [x] check google forms
  - [ ] save to xlsx
  - [ ] make a script in node.js to parse data
- [x] Check Wordpress
  - [ ] Start implementation

### 🗒️ Checklist/Additional Notes

- [x] Labeled?
- [x] Prioritized and scaled in projects?
- [ ] Milestone?
- [ ] Files provided?

**Comment by MMadejsza** [comment]
:X for google forms

**Comment by MMadejsza** [comment]
Actually for now google forms with manual content apllication.
