### ISSUE TITLE
Study Marking Criteria and follow with the report

### ISSUE THREAD

**Issue by MMadejsza** [MMadejsza/yoganka.pl#63]
### 📅 Deadline

02-12-2024

### 📝 Task Summary

- [x] Familiarize yourself with marking criteria. It's about tweaking the report approach from Bussines to University/Researcher/Engineer point of view.
- [ ] Redifine objectives with UX idea and A/B testing

### ✅ Template Checklist

- [X] Labeled in projects?
- [X] Prioritized in projects?
- [X] Scaled in projects?
- [X] Milestone assigned?
- [ ] Files provided?
